apiVersion: apps/v1
kind: Deployment
metadata:
 name: api-app-deployement
 labels:
  type: node-api-app
spec:
 template:
  metadata:
   name: api-application
   labels:
    type: node-api-app
  spec:
   containers:
    - name: app-container
      image: krishnansai/new-sag:1.0
      resources:
        limits:
          cpu: "1"
          memory: "1Gi"
        requests:
          cpu: "1"
          memory: "500Mi"
      ports:
        - containerPort: 4000
      env:
        - name: DB_HOST
          valueFrom:
           secretKeyRef:
             name: dbsecret
             key: DB_HOST
        - name: DB_USER
          valueFrom:
           secretKeyRef:
             name: dbsecret
             key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
           secretKeyRef:
             name: dbsecret
             key: DB_PASSWORD
        - name: DB_DATABASE
          valueFrom:
           secretKeyRef:
             name: dbsecret
             key: DB_DATABASE
        - name: DB_PORT
          valueFrom:
           secretKeyRef:
             name: dbsecret
             key: DB_PORT
        - name: PORT
          valueFrom:
           secretKeyRef:
             name: dbsecret
             key: PORT
 replicas: 1
 selector:
  matchLabels:
   type: node-api-app

 strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
